### ISSUE TITLE
When logo set sometime getting error immutable bitmap passed to Canvas constructor

### ISSUE THREAD

**Issue by hardikbhalodi** [alexzhirkevich/custom-qr-generator#17]
java.lang.IllegalStateException: Immutable bitmap passed to Canvas constructor
                                         	at android.graphics.Canvas.<init>(Canvas.java:114)
                                         	at com.github.alexzhirkevich.customqrgenerator.vector.QrCodeDrawableImpl.createLogo(QrCodeDrawable.kt:547)
                                         	at com.github.alexzhirkevich.customqrgenerator.vector.QrCodeDrawableImpl.resize(QrCodeDrawable.kt:490)
                                         	at com.github.alexzhirkevich.customqrgenerator.vector.QrCodeDrawableImpl.setBounds(QrCodeDrawable.kt:131)
                                         	at android.widget.ImageView.configureBounds(ImageView.java:1299)
                                         	at android.widget.ImageView.updateDrawable(ImageView.java:1084)
                                         	at android.widget.ImageView.setImageDrawable(ImageView.java:599)

**Comment by alexzhirkevich** [comment]
Check is it reproduces in `com.github.alexzhirkevich:custom-qr-generator: b6200451d6`

**Comment by hardikbhalodi** [comment]
com.github.alexzhirkevich:custom-qr-generator:b8a913a64e 

couldn't fetch it, seems not a valid dependency!

**Comment by alexzhirkevich** [comment]
Should be fixed in 1.5.7
