### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by maratkarelov** [alexzhirkevich/custom-qr-generator#2]
2022-07-29 10:18:21.322 16256-16256/com.github.alexzhirkevich.customqrgenerator.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.alexzhirkevich.customqrgenerator.example, PID: 16256
    com.github.alexzhirkevich.customqrgenerator.QrCodeCreationException
        at com.github.alexzhirkevich.customqrgenerator.QrGenerator$generateQrCodeSuspend$2.invokeSuspend(QRGenerator.kt:38)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7ecff62, Dispatchers.Main.immediate]
    Caused by: java.lang.NoSuchMethodError: No static method pack(I)J in class Landroid/graphics/Color; or its super classes (declaration of 'android.graphics.Color' appears in /system/framework/framework.jar)
        at com.github.alexzhirkevich.customqrgenerator.QrGenerator.drawBackground(QRGenerator.kt:231)
        at com.github.alexzhirkevich.customqrgenerator.QrGenerator.createQrCodeInternal(QRGenerator.kt:53)
        at com.github.alexzhirkevich.customqrgenerator.QrGenerator.access$createQrCodeInternal(QRGenerator.kt:16)
        at com.github.alexzhirkevich.customqrgenerator.QrGenerator$generateQrCodeSuspend$2$1$1.invokeSuspend(QRGenerator.kt:33)
        at com.github.alexzhirkevich.customqrgenerator.QrGenerator$generateQrCodeSuspend$2$1$1.invoke(QRGenerator.kt)
        at com.github.alexzhirkevich.customqrgenerator.QrGenerator$generateQrCodeSuspend$2$1$1.invoke(QRGenerator.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
        at com.github.alexzhirkevich.customqrgenerator.QrGenerator$generateQrCodeSuspend$2.invokeSuspend(QRGenerator.kt:32)

**Comment by alexzhirkevich** [comment]
> 2022-07-29 10:18:21.322 16256-16256/com.github.alexzhirkevich.customqrgenerator.example E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.github.alexzhirkevich.customqrgenerator.example, PID: 16256
> com.github.alexzhirkevich.customqrgenerator.QrCodeCreationException
> at com.github.alexzhirkevich.customqrgenerator.QrGenerator$generateQrCodeSuspend$2.invokeSuspend(QRGenerator.kt:38)
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
> Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7ecff62, Dispatchers.Main.immediate]
> Caused by: java.lang.NoSuchMethodError: No static method pack(I)J in class Landroid/graphics/Color; or its super classes (declaration of 'android.graphics.Color' appears in /system/framework/framework.jar)
> at com.github.alexzhirkevich.customqrgenerator.QrGenerator.drawBackground(QRGenerator.kt:231)
> at com.github.alexzhirkevich.customqrgenerator.QrGenerator.createQrCodeInternal(QRGenerator.kt:53)
> at com.github.alexzhirkevich.customqrgenerator.QrGenerator.access$createQrCodeInternal(QRGenerator.kt:16)
> at com.github.alexzhirkevich.customqrgenerator.QrGenerator$generateQrCodeSuspend$2$1$1.invokeSuspend(QRGenerator.kt:33)
> at com.github.alexzhirkevich.customqrgenerator.QrGenerator$generateQrCodeSuspend$2$1$1.invoke(QRGenerator.kt)
> at com.github.alexzhirkevich.customqrgenerator.QrGenerator$generateQrCodeSuspend$2$1$1.invoke(QRGenerator.kt)
> at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
> at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
> at com.github.alexzhirkevich.customqrgenerator.QrGenerator$generateQrCodeSuspend$2.invokeSuspend(QRGenerator.kt:32)

Can you please specify android API version?
